apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: nhutq/auth-service
          ports:
            - containerPort: 3000

  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 10 }
        - setWeight: 50
        - pause: { duration: 20 }
        - setWeight: 100