apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multicluster-microservices
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # 🔥 Clusters
          - clusters: {}
          # 🔥 Service + Env combined
          - list:
              elements:
                - service: auth
                  env: dev
                  #clusterName: in-cluster
                # - service: product
                #   env: dev
                # - service: order
                #   env: dev

                
                - service: auth
                  env: staging
                  #clusterName: k3d-staging-cluster
                #- service: auth
                #   env: prod

  template:
    metadata:
      name: '{{service}}-{{env}}-{{name}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/tqnhu4/gitops-platform.git
        targetRevision: HEAD
        path: apps/{{service}}/overlays/{{env}}

      destination:
        server: '{{server}}'
        namespace: '{{service}}-{{env}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
            - CreateNamespace=true          