apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multicluster-microservices
  namespace: argocd
spec:
  generators:
    # 🔥 Clusters
    # 🔥 Filter cluster theo env
    #- clusters: 
    #    selector:
    #      matchLabels:
    #        env: '{{env}}'
    # 🔥 Service + Env combined
    - list:
        elements:
          - service: auth
            env: dev
            cluster: k3d-dev-cluster
          # - service: product
          #   env: dev
          # - service: order
          #   env: dev

          
          - service: auth
            env: staging
            cluster: k3d-staging-cluster
          #- service: auth
          #   env: prod

  template:
    metadata:
      name: '{{service}}-{{env}}-{{cluster}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/tqnhu4/gitops-platform.git
        targetRevision: HEAD
        path: apps/{{service}}/overlays/{{env}}

      destination:
        name: '{{cluster}}'
        #server: '{{server}}'
        namespace: '{{service}}-{{env}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
            - CreateNamespace=true          