resources:
  - ../../base

namespace: auth-staging
nameSuffix: -staging

images:
  - name: nhutq/auth-service
    newTag: latest

replicas:
  - name: auth
    count: 2

configMapGenerator:
  - name: auth-config
    literals:
      - ENV=staging